### ISSUE TITLE
Multiple reference errors

### ISSUE THREAD

**Issue by exploshot** [exploshot/qwc-test#1]
I've multiple reference errors and undefined references, maybe someone have an idea to solve this.
![Screenshot from 2019-10-11 00-10-40](https://user-images.githubusercontent.com/9617859/66610368-9b64d880-ebbb-11e9-9181-c76549abcd8b.png)

**Comment by exploshot** [comment]
i've reduced the reference errors with https://github.com/exploshot/qwc-test/commit/d697c41aa997f0dc93128f64df06d178a9d61bd5 to 1.

Its following error: 
![Screenshot from 2019-10-12 02-42-32](https://user-images.githubusercontent.com/9617859/66691920-2b794f80-ec9a-11e9-909e-02d65a564f1a.png)

**Comment by exploshot** [comment]
I've tried to reproduce the failure in a small version but in this i'm able to build it successfully. So the issue is somewhere else: 

![Screenshot from 2019-10-12 17-25-31](https://user-images.githubusercontent.com/9617859/66703692-7d12f000-ed15-11e9-8758-0f6bc0cb27c1.png)
![Screenshot from 2019-10-12 17-25-39](https://user-images.githubusercontent.com/9617859/66703693-7d12f000-ed15-11e9-9e5a-aaa57f42ed1e.png)

**Comment by speqtr** [comment]
@exploshot, does compilation fail on all platforms? Or only one (Linux)?

**Comment by exploshot** [comment]
It fails on all platforms, but I've changed rocksdb to lmdb now with commit 62ca393deb0fe7f18514ae682c82758ba0dd386f
