### ISSUE TITLE
Cannot Map resize

### ISSUE THREAD

**Issue by exploshot** [exploshot/qwc-test#2]
`DB_RW_TXN_COMMIT_FAILED: mdb_txn_commit: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid`

txn to database is not commited or aborted.

Maybe same issue as https://github.com/who-biz/qwerty-lmdb/issues/4

i've set the actual mapsize to 16 MiB initially + 8 MiB for the first resize after startup.
![Screenshot from 2019-11-02 16-20-50](https://user-images.githubusercontent.com/9617859/68073088-14a3b580-fd8d-11e9-80b5-afd5b5938530.png)
second resize on Blockindex 860 (33554432 Bytes reached) will crash the Daemon.

**Comment by speqtr** [comment]
I think we should ask @who-biz to join this discussion 🙂

**Comment by exploshot** [comment]
Okay, just wanna say that when i restart the Daemon after "crash" it continues at exactly that point where it crashes.

**Comment by exploshot** [comment]
Probably an issue somewhere in https://github.com/exploshot/qwc-test/blob/master/external/lmdb/mdb.c#L3442
@speqtr

**Comment by who-biz** [comment]
I am having the same issue on my repository. I had initially removed map resizing, due to LMDB’s documentation stating pretty clearly IIRC that map resizing should never be necessary on 64-bit architecture. 

I was discussing this with @exploshot yesterday, on Discord. I looked into it a little further, and it looks like setting `writemap=True` may solve the issue as long as the database is set to flush asynchronously

**Comment by who-biz** [comment]
Monero’s implementation sets this value only on FreeBSD, for whatever reason.

**Comment by who-biz** [comment]
Once I am home I will look further into what’s going on here

**Comment by exploshot** [comment]
Writemap is not, at least not with me, have already tried that.

**Comment by who-biz** [comment]
From Lmdb docs: 

![](https://i.ibb.co/C56HzsL/PNG-image.png)

**Comment by exploshot** [comment]
Fixed by https://github.com/exploshot/qwc-test/commit/ca7fedccd7591704897e8a6ea6f9b965510e0831

**Comment by who-biz** [comment]
@speqtr, I am having some trouble getting the Database to load properly on a second run.  I've narrowed down the issue to the way that I have been handling block sync through `blockIndex.buildSparseChain`... Xecute mentioned that you probably have the most experience working with sparse files in QWC. Mind helping me figure out exactly whats going wrong?

Whats the best way to get in contact? Preferably somewhere with more real-time comms than Github. But if that doesn't work, I can open an issue on my repo.

**Comment by who-biz** [comment]
@exploshot if you've experience with sparsechain as well, or @nnian too.. open invitation if anyone can help me correct my mistake there.

**Comment by speqtr** [comment]
Hi @who-biz 🙂

I think it's better to start by opening an issue on your repo and invite me, @exploshot and @nnian to discuss it. So we can review the information that you already have and do some testing on our own. After that (if needed) we can create a chat for a more real-time communication. I think, Xecute can create a group chat on Telegram and invite all of us there.

PS: will be glad to help you in resolving that issue 👍

**Comment by who-biz** [comment]
@speqtr Thanks for the input. Will open an issue as per your suggestion, on my repository,  and we will take it from there.
